const DETAIL_API_MEAL = {
  meals: [
    {
      idMeal: '52770',
      strMeal: 'Spaghetti Bolognese',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'Italian',
      strInstructions: 'Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins. Add the garlic and mince and fry until they both brown. Add the mushrooms and herbs, and cook for another couple of mins.\r\n\r\nStir in the tomatoes, beef stock, tomato ketchup or purée, Worcestershire sauce and seasoning. Bring to the boil, then reduce the heat, cover and simmer, stirring occasionally, for 30 mins.\r\n\r\nMeanwhile, cook the spaghetti in a large pan of boiling, salted water, according to packet instructions. Drain well, run hot water through it, put it back in the pan and add a dash of olive oil, if you like, then stir in the meat sauce. Serve in hot bowls and hand round Parmesan cheese, for sprinkling on top.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg',
      strTags: 'Pasta,Meat',
      strYoutube: 'https://www.youtube.com/watch?v=-gF8d-fitkU',
      strIngredient1: 'onions',
      strIngredient2: 'olive oil',
      strIngredient3: 'garlic',
      strIngredient4: 'lean minced beef',
      strIngredient5: 'mushrooms',
      strIngredient6: 'dried oregano',
      strIngredient7: 'tomatoes',
      strIngredient8: 'hot beef stock',
      strIngredient9: 'tomato puree',
      strIngredient10: 'worcestershire sauce',
      strIngredient11: 'spaghetti',
      strIngredient12: 'parmesan',
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '2',
      strMeasure2: '1tbsp',
      strMeasure3: '1 clove',
      strMeasure4: '500g',
      strMeasure5: '90g',
      strMeasure6: '1tsp',
      strMeasure7: '400g can',
      strMeasure8: '300ml',
      strMeasure9: '1tbsp',
      strMeasure10: '1tbsp',
      strMeasure11: '350g',
      strMeasure12: 'Topping',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

const DETAIL_API_DRINK = {
  drinks: [
    {
      idDrink: '11007',
      strDrink: 'Margarita',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: 'Contemporary Classics',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.',
      strInstructionsES: null,
      strInstructionsDE: 'Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.',
      strInstructionsFR: null,
      strInstructionsIT: 'Strofina il bordo del bicchiere con la fetta di lime per far aderire il sale.\r\nAvere cura di inumidire solo il bordo esterno e cospargere di sale.\r\nIl sale dovrebbe presentarsi alle labbra del bevitore e non mescolarsi mai al cocktail.\r\nShakerare gli altri ingredienti con ghiaccio, quindi versarli delicatamente nel bicchiere.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg',
      strIngredient1: 'Tequila',
      strIngredient2: 'Triple sec',
      strIngredient3: 'Lime juice',
      strIngredient4: 'Salt',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1/2 oz ',
      strMeasure3: '1 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://commons.wikimedia.org/wiki/File:Klassiche_Margarita.jpg',
      strImageAttribution: 'Cocktailmarler',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2015-08-18 14:42:59',
    },
  ],
};

export { DETAIL_API_MEAL, DETAIL_API_DRINK };
