export const SEARCH = 'SEARCH';
export const CATEGORIES = 'CATEGORIES';
export const CATEGORY_SEARCH = 'CATEGORY_SEARCH';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_DRINKS_SUCCESS = 'FETCH_DRINKS_SUCCESS';
