const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
const FETCH_DRINKS_SUCCESS = 'FETCH_DRINKS_SUCCESS';
// const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE';

export { FETCH_DRINKS_SUCCESS, FETCH_MEALS_SUCCESS };
